#  Erasmo Cardoso da Silva
#     App Desafio Alfasolft

version: "3.8"

services:
  app:
    build:
      context: ./html
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    ports:
      - "8000:8000"

  db:
    image: mariadb:10.5
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
